name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: GuiOlialves
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%237e22ce&color_dots=%230a0a0f,%232e1065,%23581c87,%23a855f7,%23c084fc
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23c084fc&color_dots=%230a0a0f,%232e1065,%23581c87,%23a855f7,%23c084fc

      - name: Publish SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
